[package]
name = "keyboard-hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }

[dev-dependencies]
rstest = "0.19.0"

