[package]
name = "keyboard_hook"
version = "0.1.0"
edition = "2021"

[lib]
name = "keyboard_hook"
path = "src/lib.rs"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi"] }

[dev-dependencies]
rstest = "0.19.0"

